name: build-game
on: [push]
jobs:
  build-game:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install ./picotool
      - run: p8tool build ${{ secrets.PICO8_GAME_NAME }} --gfx assets.p8 --map assets.p8 --lua game.lua --empty-gff --empty-sfx --empty-music
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ secrets.PICO8_GAME_NAME }}
          path: ${{ secrets.PICO8_GAME_NAME }}
      - name: Release game build
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ secrets.PICO8_GAME_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
